import { query } from '$lib/server/convex'
import type { PageServerLoad } from './$types'

const FALLBACK_STUDENTS = [
	{
		id: 1,
		name: 'Aarav Sharma',
		attendance: 92,
		testAvg: 85,
		assignmentsDone: 18,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 88 },
			{ subject: 'Science', score: 82 },
			{ subject: 'English', score: 85 },
		],
		attendanceHistory: [95, 90, 88, 93, 91, 92],
	},
	{
		id: 2,
		name: 'Sita Adhikari',
		attendance: 88,
		testAvg: 91,
		assignmentsDone: 20,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 95 },
			{ subject: 'Science', score: 90 },
			{ subject: 'English', score: 88 },
		],
		attendanceHistory: [85, 88, 90, 87, 89, 88],
	},
	{
		id: 3,
		name: 'Bikash Thapa',
		attendance: 45,
		testAvg: 35,
		assignmentsDone: 8,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 30 },
			{ subject: 'Science', score: 38 },
			{ subject: 'English', score: 37 },
		],
		attendanceHistory: [50, 48, 42, 45, 43, 45],
	},
	{
		id: 4,
		name: 'Priya Gurung',
		attendance: 78,
		testAvg: 72,
		assignmentsDone: 16,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 70 },
			{ subject: 'Science', score: 75 },
			{ subject: 'English', score: 71 },
		],
		attendanceHistory: [80, 75, 78, 76, 79, 78],
	},
	{
		id: 5,
		name: 'Ramesh KC',
		attendance: 55,
		testAvg: 48,
		assignmentsDone: 10,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 45 },
			{ subject: 'Science', score: 50 },
			{ subject: 'English', score: 49 },
		],
		attendanceHistory: [60, 55, 52, 58, 54, 55],
	},
	{
		id: 6,
		name: 'Anita Poudel',
		attendance: 95,
		testAvg: 88,
		assignmentsDone: 19,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 90 },
			{ subject: 'Science', score: 85 },
			{ subject: 'English', score: 89 },
		],
		attendanceHistory: [93, 96, 94, 95, 96, 95],
	},
	{
		id: 7,
		name: 'Dipak Rai',
		attendance: 38,
		testAvg: 28,
		assignmentsDone: 5,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 25 },
			{ subject: 'Science', score: 30 },
			{ subject: 'English', score: 29 },
		],
		attendanceHistory: [40, 35, 38, 42, 36, 38],
	},
	{
		id: 8,
		name: 'Sunita BK',
		attendance: 82,
		testAvg: 76,
		assignmentsDone: 17,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 78 },
			{ subject: 'Science', score: 74 },
			{ subject: 'English', score: 76 },
		],
		attendanceHistory: [80, 83, 81, 84, 82, 82],
	},
	{
		id: 9,
		name: 'Kiran Tamang',
		attendance: 68,
		testAvg: 58,
		assignmentsDone: 12,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 55 },
			{ subject: 'Science', score: 60 },
			{ subject: 'English', score: 59 },
		],
		attendanceHistory: [70, 65, 68, 66, 69, 68],
	},
	{
		id: 10,
		name: 'Maya Lama',
		attendance: 90,
		testAvg: 82,
		assignmentsDone: 18,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 84 },
			{ subject: 'Science', score: 80 },
			{ subject: 'English', score: 82 },
		],
		attendanceHistory: [88, 91, 89, 90, 92, 90],
	},
	{
		id: 11,
		name: 'Sujan Shrestha',
		attendance: 73,
		testAvg: 65,
		assignmentsDone: 14,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 62 },
			{ subject: 'Science', score: 68 },
			{ subject: 'English', score: 65 },
		],
		attendanceHistory: [75, 70, 73, 72, 74, 73],
	},
	{
		id: 12,
		name: 'Nisha Magar',
		attendance: 96,
		testAvg: 94,
		assignmentsDone: 20,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 96 },
			{ subject: 'Science', score: 92 },
			{ subject: 'English', score: 94 },
		],
		attendanceHistory: [94, 97, 95, 96, 97, 96],
	},
	{
		id: 13,
		name: 'Anil Basnet',
		attendance: 60,
		testAvg: 52,
		assignmentsDone: 11,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 50 },
			{ subject: 'Science', score: 55 },
			{ subject: 'English', score: 51 },
		],
		attendanceHistory: [62, 58, 60, 61, 59, 60],
	},
	{
		id: 14,
		name: 'Sabina Dahal',
		attendance: 85,
		testAvg: 79,
		assignmentsDone: 17,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 80 },
			{ subject: 'Science', score: 78 },
			{ subject: 'English', score: 79 },
		],
		attendanceHistory: [83, 86, 84, 85, 87, 85],
	},
	{
		id: 15,
		name: 'Rajan Pokharel',
		attendance: 42,
		testAvg: 32,
		assignmentsDone: 6,
		assignmentsTotal: 20,
		testScores: [
			{ subject: 'Math', score: 28 },
			{ subject: 'Science', score: 35 },
			{ subject: 'English', score: 33 },
		],
		attendanceHistory: [45, 40, 42, 44, 41, 42],
	},
]

export const load: PageServerLoad = async ({ url }) => {
	const sectionId = url.searchParams.get('sectionId')
	const students = sectionId
		? await query('progress:getSectionProgress', { sectionId }, FALLBACK_STUDENTS)
		: FALLBACK_STUDENTS
	return { students }
}
