<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Select } from '$lib/components/ui/select';
  import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '$lib/components/ui/card';
  import { Badge } from '$lib/components/ui/badge';
  import { Label } from '$lib/components/ui/label';
  import { Separator } from '$lib/components/ui/separator';
  import { t } from '$lib/i18n/index.svelte';
  import { Download, FileText, FileSpreadsheet, Printer, CheckCircle2, Users } from 'lucide-svelte';
  import { convexQuery, isConvexConfigured, api } from '$lib/convex';
  import { getSchool } from '$lib/stores/school.svelte';

  type ExportFormat = 'csv' | 'pdf';
  type ExportScope = 'class' | 'student';

  let selectedFormat = $state<ExportFormat>('csv');
  let selectedScope = $state<ExportScope>('class');
  let selectedClass = $state('');
  let selectedExam = $state('');
  let isExporting = $state(false);
  let exportSuccess = $state(false);

  let classes = $state<{id: string; name: string; grade: number}[]>([]);

  let exams = $state<{id: string; name: string}[]>([]);

  // Convex: real test ID for the selected exam (used to fetch attempts)
  let convexTestId = $state<string | null>(null);
  // Convex: school ID (loaded from hierarchy)
  let convexSchoolId = $state<string | null>(null);
  // Convex: section ID for attendance export (first section of selected class)
  let convexSectionId = $state<string | null>(null);

  let results = $state<any[]>([]);

  const selectedClassName = $derived(classes.find(c => c.id === selectedClass)?.name ?? '');
  const selectedExamName = $derived(exams.find(e => e.id === selectedExam)?.name ?? '');

  function generateCSV(): string {
    const headers = ['Roll No', 'Student Name', 'Mathematics', 'Science', 'English', 'Nepali', 'Social Studies', 'Total', 'Percentage', 'Grade'];
    const rows = results.map(r => [r.roll, r.name, r.math, r.science, r.english, r.nepali, r.social, r.total, r.pct, r.grade].join(','));
    return [headers.join(','), ...rows].join('\n');
  }

  function downloadCSV() {
    const csv = generateCSV();
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedClassName}_${selectedExamName}_Results.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function generatePDFContent(): string {
    return `
      <html>
      <head>
        <title>${selectedClassName} - ${selectedExamName} Results</title>
        <style>
          body { font-family: system-ui, sans-serif; padding: 2rem; color: #1a1a2e; }
          h1 { text-align: center; color: #4338ca; margin-bottom: 0.25rem; }
          h2 { text-align: center; color: #6366f1; font-weight: normal; margin-top: 0; }
          .meta { text-align: center; color: #666; margin-bottom: 2rem; }
          table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
          th { background: #4338ca; color: white; padding: 0.5rem; text-align: left; }
          td { padding: 0.5rem; border-bottom: 1px solid #e5e7eb; }
          tr:nth-child(even) { background: #f9fafb; }
          .grade-a { color: #059669; font-weight: 600; }
          .grade-b { color: #d97706; font-weight: 600; }
          .grade-c { color: #dc2626; font-weight: 600; }
          .footer { margin-top: 2rem; text-align: center; font-size: 0.75rem; color: #999; }
        </style>
      </head>
      <body>
        <h1>मेरो स्कूल</h1>
        <h2>${selectedExamName}</h2>
        <p class="meta">${selectedClassName} | Academic Year 2081/82</p>
        <table>
          <thead>
            <tr>
              <th>Roll</th><th>Name</th><th>Math</th><th>Science</th><th>English</th><th>Nepali</th><th>Social</th><th>Total</th><th>%</th><th>Grade</th>
            </tr>
          </thead>
          <tbody>
            ${results.map(r => `
              <tr>
                <td>${r.roll}</td><td>${r.name}</td><td>${r.math}</td><td>${r.science}</td><td>${r.english}</td><td>${r.nepali}</td><td>${r.social}</td><td>${r.total}</td><td>${r.pct}%</td>
                <td class="${r.grade.startsWith('A') ? 'grade-a' : r.grade.startsWith('B') ? 'grade-b' : 'grade-c'}">${r.grade}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p class="footer">Generated by MeroSchool Admin | ${new Date().toLocaleDateString()}</p>
      </body>
      </html>
    `;
  }

  function downloadPDF() {
    const content = generatePDFContent();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.print();
    }
  }

  // ── Convex: load hierarchy + tests; reload results when selection changes ─────
  $effect(() => {
    if (!isConvexConfigured()) return;
    const schoolId = getSchool()?.id;
    if (!schoolId) return;

    (async () => {
      // Load school hierarchy to get real class/section IDs
      const hierarchy = await convexQuery(
        api.schools.getSchoolHierarchy,
        { schoolId },
        null as any
      );

      if (hierarchy?.schoolId) convexSchoolId = hierarchy.schoolId;

      if (hierarchy?.classes?.length) {
        classes = hierarchy.classes.map((cls: any) => ({
          id: cls._id ?? cls.id,
          name: cls.name,
          grade: cls.grade ?? 0,
        }));
        // Update selected class to first real ID
        if (classes.length > 0 && !classes.find(c => c.id === selectedClass)) {
          selectedClass = classes[0].id;
        }

        // Capture section ID for attendance export
        const matchedCls = hierarchy.classes.find((c: any) => (c._id ?? c.id) === selectedClass);
        if (matchedCls?.sections?.length) {
          convexSectionId = matchedCls.sections[0]._id ?? matchedCls.sections[0].id ?? null;
        }
      }
    })();
  });

  // Reload test attempts when selected exam or class changes
  $effect(() => {
    const examId = selectedExam;
    const classId = selectedClass;

    if (!isConvexConfigured() || !examId) return;

    (async () => {
      // Try to find a real test ID from the exams list
      const testId = convexTestId ?? examId;

      const attempts = await convexQuery(
        api.tests.listAttemptsByTest,
        { testId },
        [] as any[]
      );

      if (attempts?.length) {
        results = attempts.map((attempt: any, idx: number) => {
          const marks = attempt.marks ?? {};
          const subjects = Object.keys(marks);
          const total = subjects.reduce((s: number, k: string) => s + (marks[k] ?? 0), 0);
          const maxMarks = attempt.totalMarks ?? 500;
          const pct = maxMarks > 0 ? Math.round((total / maxMarks) * 1000) / 10 : 0;
          const grade =
            pct >= 90 ? 'A+' : pct >= 80 ? 'A' : pct >= 70 ? 'B+' :
            pct >= 60 ? 'B' : pct >= 50 ? 'C+' : pct >= 40 ? 'C' : 'D';

          return {
            roll: attempt.rollNumber ?? String(idx + 1).padStart(3, '0'),
            name: attempt.studentName ?? `Student ${idx + 1}`,
            math: marks['Mathematics'] ?? marks['math'] ?? 0,
            science: marks['Science'] ?? marks['science'] ?? 0,
            english: marks['English'] ?? marks['english'] ?? 0,
            nepali: marks['Nepali'] ?? marks['nepali'] ?? 0,
            social: marks['Social Studies'] ?? marks['social'] ?? 0,
            total,
            pct,
            grade,
          };
        });
      }
    })();
  });

  async function handleExport() {
    isExporting = true;
    exportSuccess = false;

    // If Convex is configured, try Convex CSV export endpoints first
    if (isConvexConfigured()) {
      try {
        if (selectedFormat === 'csv') {
          const schoolId = convexSchoolId ?? 'default';

          // Export students list via Convex
          const studentsCSV = await convexQuery(
            api.csv.exportStudents,
            { schoolId },
            null as any
          );

          if (studentsCSV) {
            const blob = new Blob([studentsCSV], { type: 'text/csv' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${selectedClassName}_${selectedExamName}_Students.csv`;
            a.click();
            URL.revokeObjectURL(url);

            // Also export attendance if we have a section ID
            if (convexSectionId) {
              const today = new Date().toISOString().slice(0, 10);
              const startDate = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
              const attendanceCSV = await convexQuery(
                api.csv.exportAttendance,
                { sectionId: convexSectionId, startDate, endDate: today },
                null as any
              );
              if (attendanceCSV) {
                const blob2 = new Blob([attendanceCSV], { type: 'text/csv' });
                const url2 = URL.createObjectURL(blob2);
                const a2 = document.createElement('a');
                a2.href = url2;
                a2.download = `${selectedClassName}_Attendance.csv`;
                a2.click();
                URL.revokeObjectURL(url2);
              }
            }

            isExporting = false;
            exportSuccess = true;
            setTimeout(() => { exportSuccess = false; }, 3000);
            return;
          }
        }
      } catch (err) {
        console.warn('[export] Convex export failed, falling back to local', err);
      }
    }

    // Fallback: local generation
    await new Promise(r => setTimeout(r, 800));
    if (selectedFormat === 'csv') {
      downloadCSV();
    } else {
      downloadPDF();
    }

    isExporting = false;
    exportSuccess = true;
    setTimeout(() => { exportSuccess = false; }, 3000);
  }
</script>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">{t('common.export')} - Grade Results</h1>
      <p class="text-muted-foreground mt-1">Export exam results as CSV or PDF</p>
    </div>
    <a href="/reports" class="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
      ← Back to Reports
    </a>
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <!-- Export Configuration -->
    <div class="lg:col-span-1 space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Export Settings</CardTitle>
          <CardDescription>Configure your export options</CardDescription>
        </CardHeader>
        <CardContent>
          <div class="space-y-4">
            <div>
              <Label>Format</Label>
              <div class="grid grid-cols-2 gap-2 mt-1.5">
                <Button
                  class="flex items-center gap-2 p-3 rounded-lg border-2 transition-all {selectedFormat === 'csv' ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/30'}"
                  onclick={() => selectedFormat = 'csv'}
                >
                  <FileSpreadsheet class="h-5 w-5 {selectedFormat === 'csv' ? 'text-primary' : 'text-muted-foreground'}" />
                  <div class="text-left">
                    <div class="text-sm font-medium">CSV</div>
                    <div class="text-xs text-muted-foreground">Spreadsheet</div>
                  </div>
                </Button>
                <Button
                  class="flex items-center gap-2 p-3 rounded-lg border-2 transition-all {selectedFormat === 'pdf' ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/30'}"
                  onclick={() => selectedFormat = 'pdf'}
                >
                  <FileText class="h-5 w-5 {selectedFormat === 'pdf' ? 'text-primary' : 'text-muted-foreground'}" />
                  <div class="text-left">
                    <div class="text-sm font-medium">PDF</div>
                    <div class="text-xs text-muted-foreground">Printable</div>
                  </div>
                </Button>
              </div>
            </div>

            <Separator />

            <div>
              <Label>Scope</Label>
              <div class="grid grid-cols-2 gap-2 mt-1.5">
                <Button
                  class="flex items-center gap-2 p-2.5 rounded-lg border-2 transition-all text-sm {selectedScope === 'class' ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/30'}"
                  onclick={() => selectedScope = 'class'}
                >
                  <Users class="h-4 w-4" />
                  Entire Class
                </Button>
                <Button
                  class="flex items-center gap-2 p-2.5 rounded-lg border-2 transition-all text-sm {selectedScope === 'student' ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/30'}"
                  onclick={() => selectedScope = 'student'}
                >
                  <FileText class="h-4 w-4" />
                  Per Student
                </Button>
              </div>
            </div>

            <Separator />

            <div>
              <Label>Class</Label>
              <Select class="w-full mt-1.5 rounded-md border border-input bg-background px-3 py-2 text-sm" bind:value={selectedClass} disabled={classes.length === 0}>
                {#if classes.length === 0}
                  <option value="">No classes — set up school first</option>
                {:else}
                  {#each classes as cls}
                    <option value={cls.id}>{cls.name}</option>
                  {/each}
                {/if}
              </Select>
            </div>

            <div>
              <Label>Examination</Label>
              <Select class="w-full mt-1.5 rounded-md border border-input bg-background px-3 py-2 text-sm" bind:value={selectedExam} disabled={exams.length === 0}>
                {#if exams.length === 0}
                  <option value="">No exams found</option>
                {:else}
                  {#each exams as exam}
                    <option value={exam.id}>{exam.name}</option>
                  {/each}
                {/if}
              </Select>
            </div>

            <Separator />

            <Button class="w-full" onclick={handleExport} disabled={isExporting}>
              {#if isExporting}
                <span class="animate-spin mr-2">⟳</span> Exporting...
              {:else if exportSuccess}
                <CheckCircle2 class="h-4 w-4 mr-2" /> Exported!
              {:else}
                <Download class="h-4 w-4 mr-2" /> {t('common.export')} {selectedFormat.toUpperCase()}
              {/if}
            </Button>

            {#if selectedFormat === 'pdf'}
              <Button variant="outline" class="w-full" onclick={downloadPDF}>
                <Printer class="h-4 w-4 mr-2" /> Print Preview
              </Button>
            {/if}
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Preview -->
    <div class="lg:col-span-2">
      <Card>
        <CardHeader>
          <div class="flex items-center justify-between">
            <div>
              <CardTitle>Preview</CardTitle>
              <CardDescription>{selectedClassName} — {selectedExamName}</CardDescription>
            </div>
            <Badge variant="secondary">{results.length} students</Badge>
          </div>
        </CardHeader>
        <CardContent>
          {#if results.length === 0}
            <div class="flex flex-col items-center gap-2 py-12 text-muted-foreground">
              <p class="text-sm font-medium">No data yet.</p>
              <p class="text-xs">Select a class and exam, or complete school setup first.</p>
            </div>
          {:else}
          <div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="border-b border-border">
                  <th class="text-left py-2 px-2 font-medium text-muted-foreground">Roll</th>
                  <th class="text-left py-2 px-2 font-medium text-muted-foreground">Name</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Math</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Sci</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Eng</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Nep</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Soc</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Total</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">%</th>
                  <th class="text-center py-2 px-2 font-medium text-muted-foreground">Grade</th>
                </tr>
              </thead>
              <tbody>
                {#each results as result}
                  <tr class="border-b border-border/50 hover:bg-muted/50 transition-colors">
                    <td class="py-2 px-2 font-mono text-xs">{result.roll}</td>
                    <td class="py-2 px-2 font-medium">{result.name}</td>
                    <td class="py-2 px-2 text-center">{result.math}</td>
                    <td class="py-2 px-2 text-center">{result.science}</td>
                    <td class="py-2 px-2 text-center">{result.english}</td>
                    <td class="py-2 px-2 text-center">{result.nepali}</td>
                    <td class="py-2 px-2 text-center">{result.social}</td>
                    <td class="py-2 px-2 text-center font-semibold">{result.total}</td>
                    <td class="py-2 px-2 text-center">{result.pct}%</td>
                    <td class="py-2 px-2 text-center">
                      <Badge variant={result.grade.startsWith('A') ? 'success' : result.grade.startsWith('B') ? 'warning' : 'destructive'}>
                        {result.grade}
                      </Badge>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
          {/if}
        </CardContent>
      </Card>
    </div>
  </div>
</div>
